### ISSUE TITLE
[BUG]Clock don't work

### ISSUE THREAD

**Issue by F4dhil** [ArmiaA10/Automatic-Absence#1]
Saya menemukan bug pada automatic absence yaitu pada bagian jam, menit, dan detik tidak berjalan. Saya harap bug ini dapat diselesaikan.

**Comment by ArmiaA10** [comment]
Terimakasih telah menemukan bug pada Automatic Absence. Saya telah memperbaiki bug ini sekaligus mengganti ukuran dari fontnya. Lihat gambar dibawah untuk lebih detailnya. Ini berjalan dengan baik untuk webcam dan video (.mp4). 

Note : Format jam dan tanggal mengikuti format yang ada pada local PC

![Screenshot 2021-09-15 182743](https://user-images.githubusercontent.com/83819678/133425915-6f714849-6261-47ee-9430-8093612b24ea.png)
